server:
  port: 8100
spring:
  application:
    name: testenvmanage-masternode-server
  redis:
    database: 0
    host: 172.29.7.157
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
    #????????
    lease-renewal-interval-in-seconds: 5
    #??????
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
    registry-fetch-interval-seconds: 5 #????????
mq:
  RocketMQ:                                     #RocketMQ????
    namesrvAddr: 172.29.7.157:9876    #name-server?????,????????
    groupName:  DOP_CIPIPELINE_PRODUCER_GROUP      #??????
    instanceName: DOP_CIPIPELINE                   #?????MQ??
    maxMessageSize: 131072 # 1024*128           #??????
    sendMessageTimeout: 10000                   #????????
    queueTopic: CIPIPELINE_EXECUTE_QUEUE        #???
    consumerGroup: DOP_CIPIPELINE_CONSUMER_GROUP    #???