server:
  port: 8803
spring:
  application:
    name: depanalyzerservice
  datasource:
    url: jdbc:mysql://localhost:3306/incanalysis?setUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a0014623

eureka:
  client:
    #设置注册中心的地址，注意加空格，访问地址localhost:7001
    service-url:
      defaultZone: http://172.29.7.159:6861/eureka/

web:
  file-save-path: tempDep/
  py-save-path: tempDepForPy/
  pypi-server: https://pypi.tuna.tsinghua.edu.cn/simple