server:
  port: 6811
spring:
  application:
    name: slave-agent
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/agent?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: dop
    password: Dop_mysql_12345
    driver-class-name: com.mysql.cj.jdbc.Driver

#filesystem
filesystem:
  file:
    port: 8880
  default:
    directory: F:\\aa_agent\\slaveagent\\src\\main\\resources\\zip
    filedirectory: F:\\aa_agent\\slaveagent\\src\\main\\resources\\dir
  zipfile:
    port: 8881

#toolsystem
toolsystem:
  download:
    threadNum: 10

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    prefer-ip-address: true
    #????????
    lease-renewal-interval-in-seconds: 5
    #??????
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5 #????????