spring:
  application:
    name: discovery-server  #???
server:
  port: 8761                    # ???Eureka?????
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  instance:
    hostname: ${spring.application.name}
    appname: ${spring.application.name}  #???
    lease-expiration-duration-in-seconds: 30  #??????????
    lease-renewal-interval-in-seconds: 10    #????
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000 #??????
    ## ?????????????????????????????
    ## eureka.server.renewalThresholdUpdateIntervalMs=120000
    use-read-only-response-cache: false #??read-only-response-cache
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
