server:
  port: 8804
spring:
  application:
    name: companalyzerservice

eureka:
  client:
    #设置注册中心的地址，注意加空格，访问地址localhost:7001
    service-url:
      defaultZone: http://172.29.7.159:6861/eureka/

web:
  file-save-path: tempComp/
  path: lib/
errorprone:
  errorprone-jar-name: error_prone_ant-2.0.19.jar


